project:
  type: website

website:
  title: "Machine Learning Capsule"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Foundations
        menu:
          - href: numpy_intro.qmd
            text: NumPy
          - href: pandas_intro.qmd
            text: Pandas
      - text: Supervised ML
        menu:
          - href: linear_regression.qmd
            text: Linear Regression
          - href: logistic_regression.qmd
            text: Logistic Regression
          - href: svm.qmd
            text: SVM

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    number-sections: true
